aztk/joblib.py
=> Don't use absolute path when submitting app

aztk/util.py
=> strip the heading slash

docs/10-clusters.md
aztk was misspelled as aztb, amended to correct spelling.
=> Spellchecking

aztk/utils/constants.py, cli/config.py, cli/spark/endpoints/cluster_create.py, docker-image/README.md, docs/12-docker-image.md
=> Bug: fix wrong path for global secrets

cli/config.py
=> Bug: fix loading local spark config

node_scripts/install/spark.py
=> Bug: History server parse file not exist

custom-scripts/simple.sh, node_scripts/install/install.py, node_scripts/install/scripts.py
=> Bug: fix logic for worker custom scripts

aztk/client.py
=> Bug: suppress warning datetime tzinfo warning

config/core-site.xml
=> Feature: WASB performance tune core-site.xml

LICENSE
=> Feature: add MIT license

cli/config.py
=> Bug: fix secrets shared key backwards compatibility

node_scripts/install/spark.py
=> Bug: Ensure Directories Exist Before Copying

node_scripts/core/config.py, node_scripts/requirements.txt
=> Bug: Support on node AAD Storage creds

aztk/spark/helpers/create_cluster.py, aztk/spark/models.py
=> Bug: stop using mutable default parameters

node_scripts/submit.py
=> Bug: always upload spark job logs, errors

cli/utils.py
=> Bug: Spark Job list apps exit code 0 bug

node_scripts/submit.py
=> Bug: fix spark-submit cores args

aztk/spark/client.py, aztk/spark/helpers/create_cluster.py, aztk/spark/models.py, cli/config.py, cli/spark/endpoints/job/submit.py, node_scripts/install/install.py
=> Feature: Spark add worker on master option

aztk/spark/helpers/submit.py, node_scripts/job_submission.py, node_scripts/submit.py
=> Feature: task affinity to master node

aztk/spark/helpers/job_submission.py, aztk_cli/config.py
=> Bug: fix spark job submit path

aztk_cli/config/cluster.yaml
=> Bug: fix broken spark init command

aztk_cli/config.py, aztk_cli/spark/endpoints/cluster/cluster_ssh.py
=> Bug: Remove unused ssh plugin flags

docs/sdk-examples.md, examples/sdk/sdk_example.py
=> Fix: add toolkit to sdk docs and example

README.md, account_setup.sh, aztk/models/models.py, aztk/node_scripts/setup_host.sh, aztk/version.py, aztk_cli/config/job.yaml, aztk_cli/config/secrets.yaml.template, docs/01-getting-started-script.md, docs/12-docker-image.md
=> Release: v0.7.2

CHANGELOG.md, aztk/version.py
=> Release: 0.9.0

aztk/node_scripts/Pipfile, aztk/node_scripts/Pipfile.lock, aztk/node_scripts/setup_host.sh
=> Fix: pin all node dependencies not in Pipfile

aztk/client/base/helpers/task_table.py
=> Fix: Verify Batch task has node_info

aztk/client/cluster/helpers/delete.py
=> Fix: Storage table never deleted
