Azure/aztk

config/cluster.yaml

Users who uncomment the cluster yaml will have issues with custom scripts. 
Probably need to validate the keys for cluster yaml template

Fix cluster yaml typo 

---

docs/20-spark-submit.md

Documentation amended: Use of aztk spark app logs results in an error. Correct usage is aztk spark cluster app-logs. Document amended to reflect this.

Amended documentation to correctly obtain logs

---

cli/utils.py

Fix #306 
This now looks like this:
```
Nodes                               | State               | IP:Port              | Master
------------------------------------|---------------------|----------------------|--------
tvm-3637016216_1-20180103t234355z   | waitingForStartTask | 13.67.129.164:50000  |
tvm-3637016216_2-20180103t234355z   | waitingForStartTask | 13.67.129.164:50001  |
```

Bug: fix alignment in get print cluster

---

cli/utils.py

I was just trying out the new job submission feature, and ran into a couple of crashes when running `aztk spark job list-apps`, stack traces below:
```
Traceback (most recent call last):
File "/Users/emcorrin/.virtualenvs/aztk/bin/aztk", line 11, in <module>
load_entry_point('aztk', 'console_scripts', 'aztk')()
File "/Users/emcorrin/dev/analytics/aztk/cli/entrypoint.py", line 32, in main
run_software(args)
File "/Users/emcorrin/dev/analytics/aztk/cli/entrypoint.py", line 59, in run_software
func(args)
File "/Users/emcorrin/dev/analytics/aztk/cli/spark/endpoints/spark.py", line 31, in execute
func(args)
File "/Users/emcorrin/dev/analytics/aztk/cli/spark/endpoints/job/job.py", line 76, in execute
func(args)
File "/Users/emcorrin/dev/analytics/aztk/cli/spark/endpoints/job/list_apps.py", line …
```

Fix job list-apps crashes

---

cli/config.py
cli/spark/endpoints/job/submit.py

Bug: Load default Jars for job submission CLI

---

config/spark-defaults.conf

Bug: move spark.local.dir to location usable by rstudioserver

---

aztk/spark/helpers/create_cluster.py

Bug: add plugins to cluster_install_cmd call

---

aztk/internal/cluster_data/node_data.py

fix crash if plugins don't exist

exit early if no plugins exist

---

aztk_cli/spark/endpoints/job/submit.py
docs/70-jobs.md

`--job-conf` option mentioned in the docs wasn't working.
CLI help was showing that option is named `--configuration-c`
which seems to be a result of a missing comma in option definition.

Fix job configuration option for `aztk spark job submit` command

---

aztk/client.py
aztk/models/models.py
aztk/spark/client.py
aztk/spark/models/models.py

Feature: enable mixed mode for jobs

---

aztk/utils/command_builder.py

Fix typo in command_builder 'expecity' -> 'explicitly'

---

aztk/client.py
aztk/internal/cluster_data/cluster_data.py
aztk/spark/client.py
aztk/spark/helpers/job_submission.py
aztk_cli/spark/endpoints/cluster/cluster_delete.py
aztk_cli/spark/endpoints/job/delete.py
docs/10-clusters.md
docs/50-sdk.md
docs/70-jobs.md

Feature: managed storage for clusters and jobs

---

aztk/node_scripts/docker_main.sh
aztk/node_scripts/submit.py
aztk/spark/helpers/submit.py

Bug: fix aztk cluster submit paths, imports

---

aztk/node_scripts/install/install.py
aztk/node_scripts/install/spark_container.py

Bug: azure file share not being shared with container

---

aztk/client.py
aztk/node_scripts/Pipfile
aztk/node_scripts/Pipfile.lock
aztk/node_scripts/install/create_user.py
aztk/node_scripts/requirements.txt
aztk/spark/models/models.py
aztk/utils/secure_utils.py
requirements.txt
setup.py

Fix: switch from pycryptodome to pycryptodomex

---

aztk/node_scripts/submit.py
aztk/spark/client.py
aztk/spark/helpers/submit.py
aztk_cli/spark/endpoints/cluster/cluster_submit.py
docs/20-spark-submit.md

fix #536
This change would allow the user to submit an app hosted at a remote location:
`aztk spark cluster submit [...] wasbs://path@remote/location.jar --skip-app-upload`
Or a location local to the docker container:
`aztk spark cluster submit [...] /local/to/docker_container.jar --skip-app-upload`
As well as supporting the current behaviour where the app is uploaded automatically
`aztk spark cluster submit [...] /local/absolute_path.jar`
The change involves moving the appending of "$AZ_BATCH_TASK_WORKING_DIR" to the application path to the client and only doing so if the "--skip-app-upload" flag is not set (note: the env variable is not resolved at this point since it is not known to the client). On the node, the now path is now un-altered.
Tested manually by:
* Submitting a job without …

Feature: Support passing of remote executables via aztk spark cluster submit

---

.travis.yml
.vsts-ci.yml
aztk/spark/client/cluster/helpers/diagnostics.py

Internal: update vsts build

---

.vsts-ci.yml

#651 introduced a typo into the vsts build definition causing false build fails

Fix: VSTS build definition typo

---

.vsts-ci.yml

Fix: vsts integration tests block

---

aztk/error.py
aztk/internal/cluster_data/node_data.py
aztk/models/__init__.py
aztk/models/cluster_configuration.py
aztk/models/custom_script.py
aztk/spark/models/models.py

Removing the deprecated custom scripts feature

Feature: remove custom scripts

---

aztk/client/cluster/helpers/create.py
aztk/client/job/helpers/submit.py
aztk/node_scripts/setup_host.sh

This retries docker pulls a maximum of 5 times with an exponential back-off. 
In addition to the start task retries introduced with #661, this should alleviate some issues with intermittent 
network errors when pulling docker images.
Fix #659

Feature: Spark retry docker pull

---

aztk/client/base/base_operations.py
aztk/models/__init__.py
aztk/models/cluster.py
aztk/models/cluster_state.py
aztk_cli/utils.py

Align ClusterState with the JobState and ApplicationState Enums.

Feature: ClusterState enum

---

aztk_cli/utils.py

When listing clusters I find it's useful to have the creation time in order to differentiate between similar clusters (e.g. to shut down the older one), or to make it easier to spot clusters that have been unintentionally left running.
What do you think?

Include cluster creation time in output of cluster list and cluster get

---

aztk/spark/client/base/helpers/list_applications.py
aztk/spark/client/base/operations.py
aztk/spark/client/cluster/operations.py

list_applications was previously throwing this error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "...\aztk\spark\client\base\operations.py", line 85, in list_applications
return list_applications.list_applications(self, id)
File "...\aztk\spark\client\base\helpers\list_applications.py", line 21, in list_applications
return models.Application(_list_applications(core_operations, id))
File "...\aztk\spark\client\base\helpers\list_applications.py", line 11, in _list_applications
scheduling_target = core_operations.get_cluster_configuration(id).scheduling_target
AttributeError: 'ClusterOperations' object has no attribute 'get_cluster_configuration'
```
It is now working and returns a list of tasks.

Fix: list_applications throwing error
